### PR TITLE
Multiple proposal specific delegations for same delegator and delegate

### LINKED ISSUE #109: Allow delegator to create more than one proposal-specific delegation (different proposals) with same delegate
### Problem with unique constraint on delegations?  
We have a unique constraint on delegations, using unique index: `uniq_index_org_delegator_delegate`. This constraint prevents creation of more than one proposal-specific delegation (for different `proposal_url`s) with the same delegator and delegate. In other words, a delegator cannot delegate more than one (different) proposal-specific delegations to the same delegate, which does not seem to be what we want.  

To reproduce, use iex console to create a proposal specific delegation, then try to create another with same delegator & delegate, but different proposal_url:  
```
errors: [
     org_delegator_delegate: {"has already been taken",
      [
        constraint: :unique,
        constraint_name: "uniq_index_org_delegator_delegate"
      ]}
 ...
```

### PR DESCRIPTION
**Pull request by jinjagit**
Dropping `:uniq_index_org_delegator_delegate` enabled the creation of duplicate proposal-specific delegations for the same delegator/delegate pair. I have prevented this by the creation of the unique index `:uniq_index_org_delegator_delegate_proposal` and related changeset validation.  

Much of this PR was spent on understanding the implications of this change, and trying to ensure they are covered by issue #125  

3 tests (in `test/liquid_voting/delegations_test.exs`) now failed (as expected):  
1. "create_delegation/1 with duplicate data returns error changeset" (this tests global delegation creation)  
2. "create_delegation/1 with proposal-specifc data returns error if global delegation for same delegator/delegate pair exists"
3. "create_delegation/1 with global delegation data returns error if proposal-specific delegation for same delegator/delegate pair exists"    

Since there appears to be no 'skip' option for mix tests, I have commented out these 3 tests and added detailed comments to each (which include a reference to issue #125, where all 3 of these tests should be addressed). Whilst this is not my favorite approach, it should help avoid losing these tests (or the proposed replacements).  

Closes #109

### CODE REVIEW

File: test/liquid_voting/delegations_test.exs [hunk 1]
```diff
@@ -82,17 +84,25 @@ defmodule LiquidVoting.DelegationsTest do
       assert {:ok, %Delegation{} = delegation} = Delegations.create_delegation(args)
     end
 
-    test "create_delegation/1 with duplicate data returns error changeset" do
-      original_delegation = insert(:delegation)
+    # FAILING!!
```
Comment (oliverbarnes) [inline test/liquid_voting/delegations_test.exs:87]: <3 warning

File: test/liquid_voting/delegations_test.exs [hunk 2]
```diff
@@ -82,17 +84,25 @@ defmodule LiquidVoting.DelegationsTest do
...
+    # PR #109 https://github.com/liquidvotingio/api/issues/109
+    # "Allow creation of more than one proposal-specific delegation (different proposals) with same delegator and delegate"
+    # causes this failure.
+    # Since we wish to permit the existence of both a global and a proposal-specific delegation for the same delegate/delegator
+    # pair, in certain cases (see issue # 125: https://github.com/liquidvotingio/api/issues/125, for details), this test case
+    # should actually be acceptable (and this test, therefore, should be removed/ammended appropriately)
+    #
+    # test "create_delegation/1 with duplicate data returns error changeset" do
```
Comment (oliverbarnes) [inline test/liquid_voting/delegations_test.exs:95]: You can [`@tag :skip`](https://til.hashrocket.com/posts/rzcuw0e3ba-skip-pending-tests-in-exunit)

**Review by oliverbarnes — CHANGES_REQUESTED** [review]
I just merged Dave's test refactor on https://github.com/liquidvotingio/api/pull/122, so you'll need to rebase - and solve conflicts :) basically moving tests from one file to another. Would you please solve the conflicts and ping me so I can review again?

(And a couple of other comments)

File: test/liquid_voting/delegations_test.exs (hunk 2 above)
Comment (jinjagit) [reply test/liquid_voting/delegations_test.exs:95]: > I just merged Dave's test refactor on #122, so you'll need to rebase - and solve conflicts :) basically moving tests from one file to another. Would you please solve the conflicts and ping me so I can review again?
> 
> (And a couple of other comments)

Do you mean I should pull to the branch I used for this PR?

**Comment by oliverbarnes** [comment]
> Do you mean I should pull to the branch I used for this PR?

Yes, from master:

```
git pull --rebase origin master
```

**Comment by jinjagit** [comment]
> > Do you mean I should pull to the branch I used for this PR?
> 
> Yes, from master:
> 
> ```
> git pull --rebase origin master
> ```

ah ok, then switch back to feature branch and rebase / resolve conflicts?

**Comment by oliverbarnes** [comment]
You can do that straight from the feature branch, and you'll need to resolve the conflicts during the rebase process.

If you were pulling into master and then rebasing locally, you'd do:

```
(feature-branch)$ git checkout master
(master)$ git pull
...output
(master)$ git checkout feature-branch
(feature-branch)$ git rebase master
...resolve conflicts
(feature-branch)$ git rebase --continue
(feature-branch)$ git push --force
```

**Comment by jinjagit** [comment]
@oliverbarnes Force push after rebase

File: test/liquid_voting/delegations_test.exs [hunk 3]
```diff
@@ -82,6 +84,14 @@ defmodule LiquidVoting.DelegationsTest do
       assert {:ok, %Delegation{} = delegation} = Delegations.create_delegation(args)
     end
 
+    # FAILING!!
+    # PR #109 https://github.com/liquidvotingio/api/issues/109
+    # "Allow creation of more than one proposal-specific delegation (different proposals) with same delegator and delegate"
+    # causes this failure.
+    # Since we wish to permit the existence of both a global and a proposal-specific delegation for the same delegate/delegator
+    # pair, in certain cases (see issue # 125: https://github.com/liquidvotingio/api/issues/125, for details), this test case
+    # should actually be acceptable (and this test, therefore, should be removed/ammended appropriately)
```
Comment (oliverbarnes) [inline test/liquid_voting/delegations_test.exs:93]: Actually, this test covers duplicate global delegations? So should always fail. Unless I'm missing some implication from #109 here

File: test/liquid_voting/delegations_test.exs [hunk 4]
```diff
@@ -108,6 +118,16 @@ defmodule LiquidVoting.DelegationsTest do
...
 
+    # FAILING!!
+    # PR #109 https://github.com/liquidvotingio/api/issues/109
+    # "Allow creation of more than one proposal-specific delegation (different proposals) with same delegator and delegate"
+    # causes this failure.
+    # Addressed in issue #125:https://github.com/liquidvotingio/api/issues/125
+    # This test case should actually be acceptable (should not return a changeset error), though we need to ensure (in applying
+    # issue #125, above) that the proposal-specific delegation takes precedence (to prevent double delegation counting if delegate votes)
+    # Thus, delete this test and add a new test of proposal-specific delegation takes precedence over global delegation for same
+    # delegator/delegate pair, when issue #125 is addressed.
```
Comment (oliverbarnes) [inline test/liquid_voting/delegations_test.exs:129]: Again, I might be missing something here, but - seems to me this test is still current, since if a global delegation is present, and proposal-specific one for the same delegate is redundant. In #125 we'll only allow proposal-specific ones for _different_ delegates, and those will indeed be the only ones counted when a global delegatoin for _another_ delegate is also present.

File: test/liquid_voting/delegations_test.exs [hunk 5]
```diff
@@ -122,6 +142,13 @@ defmodule LiquidVoting.DelegationsTest do
       assert {:error, %Ecto.Changeset{}} = Delegations.create_delegation(args)
     end
 
+    # FAILING!!
+    # PR #109 https://github.com/liquidvotingio/api/issues/109
+    # "Allow creation of more than one proposal-specific delegation (different proposals) with same delegator and delegate"
+    # causes this failure.
+    # Addressed in issue #125:https://github.com/liquidvotingio/api/issues/125
+    # This test should pass when #125 is addressed as the global delegation should cause the deletion of the proposal-specific delegation.
```
Comment (oliverbarnes) [inline test/liquid_voting/delegations_test.exs:150]: I think this test should actually expect something different after #125, because there won't be an error and the global delegation will be created. 

And we should assert that the original proposal-specific one will be deleted.

Maybe we can continue this discussion during implementation of #125, and just leave enough comments explaining that right now these aren't passing because of pending functionality to be implemented during #125, and that's it.

File: test/liquid_voting/delegations_test.exs [hunk 6]
```diff
@@ -135,6 +162,20 @@ defmodule LiquidVoting.DelegationsTest do
       assert {:error, %Ecto.Changeset{}} = Delegations.create_delegation(args)
     end
 
+    test "create_delegation/1 creates second different proposal-specific delegation for same delegator/delegate pair",
```
Comment (oliverbarnes) [inline test/liquid_voting/delegations_test.exs:165]: 👍

**Review by oliverbarnes — CHANGES_REQUESTED** [review]
I think there's some confusion in warning comments :) my own head is hurting thinking of the permutations.

File: test/liquid_voting/delegations_test.exs (hunk 3 above)
Comment (jinjagit) [reply test/liquid_voting/delegations_test.exs:93]: Yes, you are right. I need to change the comments to this test.

File: test/liquid_voting/delegations_test.exs (hunk 4 above)
Comment (jinjagit) [reply test/liquid_voting/delegations_test.exs:129]: You mean that number 1, we agreed in #125: "If a proposal-specific delegation is created, then an existing global delegation for same delegator/delegate pair should persist, but proposal-specific delegation takes precedence (when voting result is calculated)."  
Is not quite right?  
Instead, we should prevent creation of a proposal-specific delegation, if there is an existing global delegation for same delegator/delegate pair?

File: test/liquid_voting/delegations_test.exs (hunk 5 above)
Comment (jinjagit) [reply test/liquid_voting/delegations_test.exs:150]: Yes, my comments only explain why it fails now, and why it will pass again after #125. I will add to comments to explain we need new assertions after #125.

File: test/liquid_voting/delegations_test.exs (hunk 4 above)
Comment (oliverbarnes) [reply test/liquid_voting/delegations_test.exs:129]: Exactly.

File: test/liquid_voting/delegations_test.exs (hunk 5 above)
Comment (oliverbarnes) [reply test/liquid_voting/delegations_test.exs:150]: No need to add to comments about future tests, it's really out of scope here. Let's just add the tests on #125.

File: test/liquid_voting/delegations_test.exs (hunk 3 above)
Comment (jinjagit) [reply test/liquid_voting/delegations_test.exs:93]: I'm wondering if I should create a separate issue for this ("Prevent duplicate global delegations")?

Comment (oliverbarnes) [reply test/liquid_voting/delegations_test.exs:93]: At this point I think it'll just add to the confusion :). I'd just wrap up this PR with more general comments, and get started on #125. I tried clarifying the constraints on slack and I'll post the conclusions on that issue later

**Comment by jinjagit** [comment]
This PR has raised a number of questions about other issues related to delegations, some of which are covered by #125, and some of which are alluded to in comments to skipped tests. There may be more, or less, to consider, following ongoing discussions.

File: test/liquid_voting/delegations_test.exs (hunk 3 above)
Comment (jinjagit) [reply test/liquid_voting/delegations_test.exs:93]: Can I just push the comment change for this test? (it's factually wrong at the moment)

Comment (oliverbarnes) [reply test/liquid_voting/delegations_test.exs:93]: yeah, just axe any mention of future functionality. Just state that it's failing now pending new work on #125

**Comment by jinjagit** [comment]
I have simplified the comments on the skipped tests, as suggested by @oliverbarnes

**Comment by jinjagit** [comment]
This PR remains ready for review. I think I have addressed all changes suggested  thus far.

File: mix.lock [hunk 7]
```diff
@@ -10,7 +10,7 @@
...
   "dataloader": {:hex, :dataloader, "1.0.8", "114294362db98a613f231589246aa5b0ce847412e8e75c4c94f31f204d272cbf", [:mix], [{:ecto, ">= 3.4.3 and < 4.0.0", [hex: :ecto, repo: "hexpm", optional: true]}, {:telemetry, "~> 0.4", [hex: :telemetry, repo: "hexpm", optional: false]}], "hexpm", "eaf3c2aa2bc9dbd2f1e960561d616b7f593396c4754185b75904f6d66c82a667"},
   "db_connection": {:hex, :db_connection, "2.2.2", "3bbca41b199e1598245b716248964926303b5d4609ff065125ce98bcd368939e", [:mix], [{:connection, "~> 1.0.2", [hex: :connection, repo: "hexpm", optional: false]}], "hexpm", "642af240d8a8affb93b4ba5a6fcd2bbcbdc327e1a524b825d383711536f8070c"},
-  "decimal": {:hex, :decimal, "1.9.0", "83e8daf59631d632b171faabafb4a9f4242c514b0a06ba3df493951c08f64d07", [], [], "hexpm", "b1f2343568eed6928f3e751cf2dffde95bfaa19dd95d09e8a9ea92ccfd6f7d85"},
+  "decimal": {:hex, :decimal, "1.9.0", "83e8daf59631d632b171faabafb4a9f4242c514b0a06ba3df493951c08f64d07", [:mix], [], "hexpm", "b1f2343568eed6928f3e751cf2dffde95bfaa19dd95d09e8a9ea92ccfd6f7d85"},
```
Comment (oliverbarnes) [inline mix.lock:13]: this is out of scope, but to expedite things I'll merge this time

**Review by oliverbarnes — APPROVED** [review]

File: mix.lock (hunk 7 above)
Comment (jinjagit) [reply mix.lock:13]: I'm guessing that was the result of git pull on master, before creating the branch.

Comment (oliverbarnes) [reply mix.lock:13]: That sounds right. And it's a tiny `mix.lock` format change, the dependency version and checksum didn't even change. But it's still unrelated to the feature implementation. Just a good habit to separate dependency management from feature updates. Unless the feature depends on it
